name: QooL
version: '${project.version}'
main: gg.sap.smp.qool.QoolPlugin
api-version: 1.19
authors: [ "d2a <hi@d2a.io>" ]
description: some qool improvements
website: https://qwer.tz

commands:
  trash:
    description: "Opens a trash can"
  devnull:
    description: "Setup /dev/null"
    aliases:
      - 'dev/null'
  dump:
    description: "Dump items to nearby containers"
  magnet:
    description: "Suck items yes nice"
  quickcraft:
    aliases:
      - qc
      - qcc
      - qcc->
      - qccs
      - qccs->
    description: "Craft things quickly."
  quicksched:
    description: "Quick Craft but task yes"
    aliases:
      - qs
      - qsb
      - qsbo
  exchange:
    aliases:
      - ex
    description: "Exchange items"